opt_in_rules:
  - anonymous_argument_in_multiline_closure
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - convenience_type
  - direct_return
  - discarded_notification_center_observer
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - identifier_name
  - implicit_return
  - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - let_var_whitespace
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - no_grouping_extension
  - non_overridable_class_declaration
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - period_spacing
  - prefer_key_path
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_subject
  - private_swiftui_state
  - prohibited_interface_builder
  - prohibited_super_call
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - required_enum_case
  - redundant_type_annotation
  - redundant_nil_coalescing
  - self_binding
  - shorthand_argument
  - sorted_first_last
  - static_operator
  - strict_fileprivate
  - superfluous_else
  - toggle_bool
  - unavailable_function
  - unhandled_throwing_task
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - weak_delegate
  - yoda_condition

custom_rules:
  space_after_opening_brace:
    included: ".*\\.swift"
    name: "Brace Space"
    message: "Opening brace should be followed by a space or a newline"
    regex: "\\{[^ \n\r\\}]"
    match_kinds:
      - argument
      - identifier
      - keyword
      - parameter
    severity: warning

  empty_first_line:
    name: "Empty First Line"
    message: "There should be an empty line after a declaration"
    regex: "(^[ a-zA-Z ]*(?:class) (?!(?:var|let))[ a-zA-Z:]*\\{\n *\\S+)"

  auto_generated_leftovers:
    name: "Empty Methods"
    message: "Delete auto-generated functions that you don't use"
    regex: 'func [^\n]*\{\n(\s*super\.[^\n]*\n(\s*\/\/[^\n]*\n)*|(\s*\/\/[^\n]*\n)+)\s*\}'

# Additional rules without enforcing
#
# Always use `self.` to prefix access to instance variables
# Optionally use `self.` to prefix method calls. Default to not prefixing unless really needed.
#
# All class type declarations should have an empty line after and before `{` and `}` respectively.
# For enums and structs this is optional, the larger the more likely to have empty lines padding.
#

# Rule configuration
colon:
  apply_to_dictionaries: false
cyclomatic_complexity:
  ignores_case_statements: true
identifier_name:
   # All small words used in our app and acceptable abbreviation excluded
  excluded: [x, y, i, j, k, v, at, to, ok, id, op, up, ne, sw, vc]
  min_length:
    0
  max_length:
    warning: 50
type_name:
  excluded: [ID]
  allowed_symbols: [_]
  max_length:
    warning: 50
line_length:
  warning: 180
  error: 300
file_length:
  warning: 500
statement_position:
  statement_mode: uncuddled_else
large_tuple:
  warning: 3
